import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import { ApplicationProvider } from "./presentation/applicationProvider";
import { ApplicationContainer } from "./di";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApplicationProvider container={ApplicationContainer}>
          <header> </header>

          <nav>
            <Link href="/presentation/todos">Todos</Link> |
            <Link href="/">About</Link>
          </nav>
        </ApplicationProvider>
        {children}</body>
    </html>
  );
}
