'use client';

import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

import { ApplicationContainer } from './di';
import { useState } from 'react';
import { ApplicationProvider } from './presentation/applicationProvider';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApplicationProvider container={ApplicationContainer}>
          <div>
            <header> </header>
            <nav>
              <Link href="/presentation/todos">Todos</Link> |
              <Link href="/">About</Link>
            </nav>
          </div>
          {children}
        </ApplicationProvider>
      </body>
    </html>
  );
}
